branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

max_jobs: 1

image: Visual Studio 2015

clone_depth: 1

install:
  - cinst imagemagick -PackageParameters LegacySupport=true
  - cinst ghostscript
  - powershell -Command "echo (gci 'C:\Program Files\gs' -Include 'bin' -Directory -Recurse).FullName"
  - cinst xpdf-utils
  #- cinst -y miktex
  - refreshenv
  - set
  - compare -version
  - gswin64c -v
  - pdfinfo -v
  - mpm --admin --update-db
  - mpm --admin --upgrade --package-level=basic
  - mpm --admin --update
  - initexmf --admin --enable-installer

build_script:
  - C:\MinGW\msys\1.0\bin\make install CONTINUE=y

test_script:
 - echo No tests yet...
