branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

max_jobs: 1

image: Visual Studio 2015

clone_depth: 1

install:
  - cinst imagemagick
  - cinst ghostscript
  - cinst xpdf-utils
  - cinst -y miktex
  - refreshenv
  - set
  - mpm --admin --update-db
  - mpm --admin --upgrade --package-level=complete
  - mpm --admin --update

build_script:
  - C:\MinGW\msys\1.0\bin\make install CONTINUE=y

test_script:
 - echo No tests yet...
