branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

max_jobs: 1

image: Visual Studio 2015

clone_depth: 1

install:
  - cinst imagemagick -PackageParameters LegacySupport=true
  - cinst ghostscript
  - ps: >-
      $GsPath = (gci 'C:\Program Files\gs' -Include 'bin' -Directory -Recurse | select -f 1).FullName;
      $OldPath = [Environment]::GetEnvironmentVariable('path', 'machine');
      $NewPath = $OldPath + ';' + $GsPath;
      [Environment]::SetEnvironmentVariable('path', $NewPath, 'machine');
  - cinst xpdf-utils
  - cinst -y miktex
  - refreshenv
  - set
  - compare -version
  - gswin64c -v
  - where pdfinfo
  - ps: >-
      $OldErrorActionPreference = $ErrorActionPreference;
      $ErrorActionPreference = "Continue";
      pdfinfo -v 2>&1 | %{ "$_" };
      if ($LastExitCode -ne 0 -And $LastExitCode -ne 99) {
        $host.SetShouldExit($LastExitCode);
      }
      $ErrorActionPreference = $OldErrorActionPreference;
  - mpm --admin --update-db
  - mpm --admin --upgrade --package-level=basic
  - mpm --admin --update
  - initexmf --admin --enable-installer
  - initexmf --admin --update-fndb
  - ps: >-
      $MsysPath = 'C:\MinGW\msys\1.0\bin';
      $OldPath = [Environment]::GetEnvironmentVariable('path', 'machine');
      $NewPath = $OldPath + ';' + $MsysPath;
      [Environment]::SetEnvironmentVariable('path', $NewPath, 'machine');
  - refreshenv
  - ps: >-
      $OldErrorActionPreference = $ErrorActionPreference;
      $ErrorActionPreference = "Continue";
      cmd.exe /c "kpsewhich --var-value TEXMFHOME 2>&1" 2>&1 | %{ "$_" };
      $ErrorActionPreference = $OldErrorActionPreference;
  - ps: >-
      $OldErrorActionPreference = $ErrorActionPreference;
      $ErrorActionPreference = "Continue";
      cmd.exe /c "kpsewhich --var-value TEXMFLOCAL 2>&1" 2>&1 | %{ "$_" };
      $ErrorActionPreference = $OldErrorActionPreference;

build_script:
  - pdflatex -help
  - make install CONTINUE=y
  - initexmf --admin --update-fndb

test_script:
 - make -C test


on_finish:
 - dir test\.build
 - dir test\.build\listings
 - dir test\.build\listings\test_custom_listings_caption_1
