branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

max_jobs: 1

image: Visual Studio 2015

clone_depth: 1


environment:
  deploy_key_secret:
    secure: oUQd0vmgGMlZagBkEVim8K75YMyxu/bvTi6drd6SGbyo3ek14qnJNB7aJ6iFQOJE


# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  # Decrypt deploy key
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt appveyor-deploy-key.enc -secret %deploy_key_secret% -out %USERPROFILE%\.ssh\id_rsa
  - ssh -o StrictHostKeyChecking=no -T git@github.com

  - cinst imagemagick -PackageParameters LegacySupport=true
  - cinst ghostscript
  - ps: >-
      $GsPath = (gci 'C:\Program Files\gs' -Include 'bin' -Directory -Recurse | select -f 1).FullName;
      $OldPath = [Environment]::GetEnvironmentVariable('path', 'machine');
      $NewPath = $OldPath + ';' + $GsPath;
      [Environment]::SetEnvironmentVariable('path', $NewPath, 'machine');
  - cinst xpdf-utils
  - cinst -y miktex
  - refreshenv
  - set
  - compare -version
  - gswin64c -v
  - where pdfinfo
  - ps: >-
      $OldErrorActionPreference = $ErrorActionPreference;
      $ErrorActionPreference = "Continue";
      pdfinfo -v 2>&1 | %{ "$_" };
      if ($LastExitCode -ne 0 -And $LastExitCode -ne 99) {
        $host.SetShouldExit($LastExitCode);
      }
      $ErrorActionPreference = $OldErrorActionPreference;
  - mpm --admin --update-db
  #- mpm --admin --upgrade --package-level=basic
  # ps
  #    mpm --admin --find-updates | foreach { $_.ToString() } | select-string "^(?!miktex.*$)" > upd-packages.txt
  #- mpm --admin --update-some=upd-packages.txt --verbose
  - initexmf --admin --enable-installer --verbose
  - initexmf --admin --update-fndb --verbose
  - initexmf --admin --mkmaps --verbose
  - pdflatex -version
  - ps: >-
      $MsysPath = 'C:\MinGW\msys\1.0\bin';
      $OldPath = [Environment]::GetEnvironmentVariable('path', 'machine');
      $NewPath = $OldPath + ';' + $MsysPath;
      [Environment]::SetEnvironmentVariable('path', $NewPath, 'machine');
  - refreshenv
  - ps: >-
      $OldErrorActionPreference = $ErrorActionPreference;
      $ErrorActionPreference = "Continue";
      cmd.exe /c "kpsewhich --var-value TEXMFHOME 2>&1" 2>&1 | %{ "$_" };
      cmd.exe /c "kpsewhich --var-value TEXMFLOCAL 2>&1" 2>&1 | %{ "$_" };
      psexec -l kpsewhich --var-value TEXMFLOCAL 2>&1 | %{ "$_" };
      $ErrorActionPreference = $OldErrorActionPreference;

build_script:
  - make install CONTINUE=y
  - initexmf --admin --update-fndb --verbose

test_script:
  - make -C test

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
