language: python

git:
  depth: 1

matrix:
  include:
    #- os: linux
    #  sudo: required
    #  python: 2.7
    - os: osx
      sudo: required
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
    fi
  - brew update
  - brew uninstall python
  - brew install python --universal --framework
  - python -v
  - brew cask install -v basictex
  - ls -la /Library/TeX
  - ls -la /Library/TeX/Distributions
  - ls -la /Library/TeX/Distributions/Programs
  - ls -la /Library/TeX/Distributions/.DefaultTeX
  - ls -la /Library/TeX/Distributions/.DefaultTeX/Contents
  - ls -la /Library/TeX/Distributions/.DefaultTeX/Contents/Programs
  - (cd /Library/TeX/Distributions && find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g')
  - export PATH=/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:$PATH
  - sudo -i tlmgr update --self --all
  - tlmgr conf
  - make install CONTINUE=y
script:
  - make -C test
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-after.sh
    fi
