language: python
python:
  - "2.7"
sudo: true
before_install:
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  - sudo apt-get update
  - sudo apt-get install --fix-missing
  - sudo apt-get install --no-install-recommends -qq poppler-utils ghostscript imagemagick --fix-missing
  - sudo apt-get install --no-install-recommends -qq libfile-fcntllock-perl gcc equivs libwww-perl fontconfig unzip
  - pdfinfo -v
  - compare -version
  - gs -v
  - export WGETRC="$(realpath .wgetrc)"
  - sudo ./install-tl-ubuntu --only-apt-and-dpkg
  - wget http://mirror.utexas.edu/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz -O install-tl-unx.tar.gz
  - tar -xf "install-tl-unx.tar.gz"
  - tl_dir=$( ls | grep -P "install-tl-\d{8}$" | head -n 1 )
  - cd "${tl_dir}"
install:
  - (echo "i" | sudo ./install-tl -v -logfile install-tl.log) || (cat wget.log)
  - MAINTEXDIR=$(grep "TEXDIR:" "install-tl.log" | awk -F'"' '{ print $2 }')
  - sudo ln -s "${MAINTEXDIR}/bin"/* "/opt/texbin"
  - sudo sed -i 's/^PATH="/PATH="\/opt\/texbin:/' /etc/environment
  - cd ..
  - source /etc/environment
  - source /etc/profile
  - source ~/.profile
  - sudo texhash
  - sudo -i tlmgr update --self --all
  - tlmgr conf
  - make install CONTINUE=y
script:
  - make -C test
