language: python

git:
  depth: 1

matrix:
  include:
    #- os: linux
    #  sudo: required
    #  python: 2.7
    - os: osx
      sudo: required
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
    fi
  - brew update
  - brew uninstall python
  - brew install python --universal --framework
  - python -v
  - brew cask install basictex
  - sudo -i texhash
  - sudo -i tlmgr update --self --all
  - tlmgr conf
  - make install CONTINUE=y
script:
  - make -C test
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-after.sh
    fi
