language: python

git:
  depth: 1

matrix:
  include:
    #- os: linux
    #  sudo: required
    #  python: 2.7
    - os: osx
      sudo: required
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
    fi
  - openssl aes-256-cbc -K $encrypted_95d1ac70cca8_key -iv $encrypted_95d1ac70cca8_iv -in ci/travis-deploy-key.enc -out travis-deploy-key -d
  - chmod 600 travis-deploy-key
  - eval `ssh-agent -s`
  - ssh-add travis-deploy-key
  - ssh-add -l
  - ssh -o StrictHostKeyChecking=no -T git@github.com
  - exit 1
  - brew update
  - brew uninstall python
  - brew install python --universal --framework
  - python -v
  - brew install libidn
  - brew install ghostscript
  - gs -v
  - brew install imagemagick
  - compare -version
  - brew install xpdf
  - pdfinfo -v || (exit 0)
  - brew cask install -v basictex
  #- export PATH=/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:$PATH
  - export PATH=/Library/TeX/Distributions/Programs/texbin:$PATH
  - sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  - sudo -i tlmgr update --self --all
  - sudo tlmgr install
      collection-basic
      collection-bibtexextra
      collection-binextra
      collection-fontsextra
      collection-fontsrecommended
      collection-fontutils
      collection-formatsextra
      collection-langenglish
      collection-langeuropean
      collection-langother
      collection-latex
      collection-latexextra
      collection-latexrecommended
      collection-mathscience
      collection-metapost
      collection-pictures
      collection-plaingeneric
      collection-pstricks
  - tlmgr conf
  - make install CONTINUE=y
script:
  - make -C test
after_script:
  - ci/travis-after.sh
